package project.managment.system;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.managment.system.Helper;
import project.managment.system.ManagerHome;
import project.managment.system.Task;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aya Ebrahim
 */
public class addTaskManager extends javax.swing.JFrame {

    /**
     * Creates new form addTaskManager
     */
    public ArrayList<String> tempMembers= new ArrayList<>();
    public ArrayList<String> tempResources= new ArrayList<>();

    public addTaskManager() {
        initComponents();
          this.setSize(800, 700);
        ResourcesLbl.setText("");
        memberIdLbl1.setText("");
        projectIdComboBox.removeAll();
        for (int i = 0; i < Helper.arrProjects.size(); i++){
            projectIdComboBox.addItem(String.valueOf(Helper.arrProjects.get(i).getId()));
        }
       
        memberIdCmb.removeAll();
        for (int i = 0; i < Helper.arrTeamMember.size(); i++){
            memberIdCmb.addItem(String.valueOf(Helper.arrTeamMember.get(i).getId()));
        }
        
        resourcesIdcmb.removeAll();
        for (int i = 0; i < Helper.arrResource.size(); i++){
        if(Helper.arrResource.get(i).getState().getClass()==availableState.class)
        {
            resourcesIdcmb.addItem(String.valueOf(Helper.arrResource.get(i).getId()));}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        projectIdComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        projectNameLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fromDateTxt = new javax.swing.JTextField();
        toDateTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        memberIdCmb = new javax.swing.JComboBox();
        resourcesIdcmb = new javax.swing.JComboBox();
        addResourcesIdBtn = new javax.swing.JButton();
        addMemberIdBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ResourcesLbl = new javax.swing.JLabel();
        memberIdLbl1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add Task");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(212, 41, 161, 50);

        jButton4.setText("<-----");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(12, 31, 67, 25);

        jLabel2.setText("Project ID ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 161, 60, 16);

        projectIdComboBox.setMaximumRowCount(100);
        projectIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectIdComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(projectIdComboBox);
        projectIdComboBox.setBounds(248, 164, 90, 22);

        jLabel3.setText("Project Name ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(44, 211, 81, 16);
        getContentPane().add(projectNameLbl);
        projectNameLbl.setBounds(248, 204, 205, 32);

        jLabel4.setText("From Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(44, 273, 60, 16);

        jLabel5.setText("To Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(44, 318, 45, 16);

        fromDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromDateTxtActionPerformed(evt);
            }
        });
        getContentPane().add(fromDateTxt);
        fromDateTxt.setBounds(248, 270, 89, 22);
        getContentPane().add(toDateTxt);
        toDateTxt.setBounds(248, 315, 89, 22);

        jLabel6.setText("Member ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(44, 366, 63, 16);

        jLabel7.setText("Resources ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(44, 412, 75, 16);

        memberIdCmb.setMaximumRowCount(100);
        getContentPane().add(memberIdCmb);
        memberIdCmb.setBounds(248, 367, 89, 22);

        resourcesIdcmb.setMaximumRowCount(100);
        getContentPane().add(resourcesIdcmb);
        resourcesIdcmb.setBounds(248, 409, 89, 22);

        addResourcesIdBtn.setText("Add");
        addResourcesIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResourcesIdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addResourcesIdBtn);
        addResourcesIdBtn.setBounds(411, 408, 73, 25);

        addMemberIdBtn.setText("Add");
        addMemberIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberIdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addMemberIdBtn);
        addMemberIdBtn.setBounds(411, 366, 73, 25);

        jButton1.setText("Add Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(212, 483, 85, 25);
        getContentPane().add(ResourcesLbl);
        ResourcesLbl.setBounds(510, 400, 110, 32);
        getContentPane().add(memberIdLbl1);
        memberIdLbl1.setBounds(510, 360, 110, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tasksManager c= new tasksManager();
        c.show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void fromDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromDateTxtActionPerformed

    private void projectIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectIdComboBoxActionPerformed
        // TODO add your handling code here:
        int i =projectIdComboBox.getSelectedIndex();
        projectNameLbl.setText(Helper.arrProjects.get(i).getName());
    }//GEN-LAST:event_projectIdComboBoxActionPerformed

    private void addMemberIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberIdBtnActionPerformed
        // TODO add your handling code here:
        
        tempMembers.add((String)memberIdCmb.getSelectedItem());
        memberIdLbl1.setText(memberIdLbl1.getText()+" ,"+(String)memberIdCmb.getSelectedItem());
        memberIdCmb.removeItemAt(memberIdCmb.getSelectedIndex());
    }//GEN-LAST:event_addMemberIdBtnActionPerformed

    private void addResourcesIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResourcesIdBtnActionPerformed
        // TODO add your handling code here:
        tempResources.add((String)resourcesIdcmb.getSelectedItem());
        ResourcesLbl.setText(ResourcesLbl.getText()+" ,"+(String)resourcesIdcmb.getSelectedItem());
         resourcesIdcmb.removeItemAt(resourcesIdcmb.getSelectedIndex());

    }//GEN-LAST:event_addResourcesIdBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reservedState r = new reservedState();
        try {
            if(Helper.arrTask.size()==0){
                Task t = new Task(1 ,
                    Integer.parseInt((String)projectIdComboBox.getSelectedItem()),
                    projectNameLbl.getText(),
                    new SimpleDateFormat("dd/MM/yyyy").parse(fromDateTxt.getText())
                    , new SimpleDateFormat("dd/MM/yyyy").parse(toDateTxt.getText())
                    , tempMembers.toArray(new String[tempMembers.size()])
                    , tempResources.toArray(new String[tempResources.size()])
                    , "In progress");
                    Manager.addTask(t);
            }
            else{
            
            Task t = new Task(Helper.arrTask.get(Helper.arrTask.size()-1).getId()+1 ,
                    Integer.parseInt((String)projectIdComboBox.getSelectedItem()),
                    projectNameLbl.getText(),
                    new SimpleDateFormat("dd/MM/yyyy").parse(fromDateTxt.getText())
                    , new SimpleDateFormat("dd/MM/yyyy").parse(toDateTxt.getText())
                    , tempMembers.toArray(new String[tempMembers.size()])
                    , tempResources.toArray(new String[tempResources.size()])
                    , "In progress");
             Manager.addTask(t);
            }
            
            
            for (int i = 0; i < tempResources.size(); i++) {
                for (int j = 0; j < Helper.arrResource.size(); j++) {
                    if(Helper.arrResource.get(j).getId()== Integer.parseInt(tempResources.get(i)))
                    {
                        Resource rr = Helper.arrResource.get(j);
                        r.doAction(rr);
                    }
                }
                
            }
        } catch (ParseException ex) {
            Logger.getLogger(addTaskManager.class.getName()).log(Level.SEVERE, null, ex);
        }
       tasksManager mh = new tasksManager();
       mh.show();
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addTaskManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addTaskManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addTaskManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addTaskManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTaskManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ResourcesLbl;
    private javax.swing.JButton addMemberIdBtn;
    private javax.swing.JButton addResourcesIdBtn;
    private javax.swing.JTextField fromDateTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox memberIdCmb;
    private javax.swing.JLabel memberIdLbl1;
    private javax.swing.JComboBox projectIdComboBox;
    private javax.swing.JLabel projectNameLbl;
    private javax.swing.JComboBox resourcesIdcmb;
    private javax.swing.JTextField toDateTxt;
    // End of variables declaration//GEN-END:variables
}
