/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.managment.system;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static project.managment.system.Helper.arrTask;

/**
 *
 * @author Aya Ebrahim
 */
public class managerEditTask extends javax.swing.JFrame {

    /**
     * Creates new form managerEditTask
     */
    int index;
    public ArrayList<String> tempMembers= new ArrayList<>();
    public ArrayList<String> tempResources= new ArrayList<>();
    public managerEditTask() {
        initComponents();
        this.setSize(800, 700);
        this.index = tasksManager.index;
        currentMembersLbl.setText("");
        currentMembersLbl.setText("");
        taskIdLbl2.setText(String.valueOf(Helper.arrTask.get(index).getId()));
        
        projectIdLbl.setText(String.valueOf(Helper.arrTask.get(index).getProjectId()));
        
        for (int i = 0; i < Helper.arrProjects.size(); i++) {
            if(Helper.arrProjects.get(i).getId()==Helper.arrTask.get(index).getProjectId()){
                
                 projectNameLbl1.setText(String.valueOf(Helper.arrProjects.get(i).getName())); 
            }
             }
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        fromDateLbl1.setText(String.valueOf(dateFormat.format(arrTask.get(index).getFromDate())));
        toDateTxt.setText(String.valueOf(dateFormat.format(arrTask.get(index).getToDate())));
        oldMemberLbl3.setText("");
        String [] a = Helper.arrTask.get(index).getMemberId();
        for (int i = 0; i < a.length; i++){
            oldMemberLbl3.setText(oldMemberLbl3.getText()+","+a[i]);
        }
        
          oldResourcesLbl.setText("");
         String [] b = Helper.arrTask.get(index).getResourcesId();
        for (int i = 0; i < b.length; i++){
            oldResourcesLbl.setText(oldResourcesLbl.getText()+","+b[i]);
        }

        memberIdCmb.removeAll();
        for (int i = 0; i < Helper.arrTeamMember.size(); i++){
            memberIdCmb.addItem(String.valueOf(Helper.arrTeamMember.get(i).getId()));
        }
        
        resourcesIdcmb.removeAll();
        for (int i = 0; i < Helper.arrResource.size(); i++){
        if(Helper.arrResource.get(i).getState().getClass()==availableState.class)
        {
            resourcesIdcmb.addItem(String.valueOf(Helper.arrResource.get(i).getId()));}    
        }
        String [] c = Helper.arrTask.get(index).getResourcesId();
            for (int j = 0; j < c.length; j++){
                resourcesIdcmb.addItem(c[j]);
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        toDateTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        memberIdCmb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        resourcesIdcmb = new javax.swing.JComboBox();
        addResourcesIdBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addMemberIdBtn = new javax.swing.JButton();
        projectIdLbl = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        projectNameLbl1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fromDateLbl1 = new javax.swing.JLabel();
        taskIdLbl2 = new javax.swing.JLabel();
        currentMembersLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        oldMemberLbl3 = new javax.swing.JLabel();
        currentResourcesLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        oldResourcesLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setText("To Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(44, 318, 45, 16);
        getContentPane().add(toDateTxt);
        toDateTxt.setBounds(250, 320, 89, 22);

        jLabel6.setText("Member ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(44, 428, 63, 16);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Edit Task");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 20, 161, 50);

        jLabel7.setText("Resources ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 520, 75, 16);

        backBtn.setText("<-----");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(12, 31, 67, 25);

        memberIdCmb.setMaximumRowCount(100);
        getContentPane().add(memberIdCmb);
        memberIdCmb.setBounds(256, 429, 70, 22);

        jLabel2.setText("Project ID ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 161, 60, 16);

        resourcesIdcmb.setMaximumRowCount(100);
        getContentPane().add(resourcesIdcmb);
        resourcesIdcmb.setBounds(250, 520, 80, 22);

        addResourcesIdBtn.setText("Add");
        addResourcesIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResourcesIdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addResourcesIdBtn);
        addResourcesIdBtn.setBounds(400, 520, 73, 25);

        jLabel3.setText("Project Name ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(44, 211, 81, 16);

        addMemberIdBtn.setText("Add");
        addMemberIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberIdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addMemberIdBtn);
        addMemberIdBtn.setBounds(400, 430, 73, 25);
        getContentPane().add(projectIdLbl);
        projectIdLbl.setBounds(240, 160, 205, 32);

        saveBtn.setText("Save ");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn);
        saveBtn.setBounds(310, 610, 85, 25);

        jLabel4.setText("From Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(44, 273, 60, 16);
        getContentPane().add(projectNameLbl1);
        projectNameLbl1.setBounds(250, 210, 205, 32);

        jLabel8.setText("Task ID ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(44, 111, 47, 16);
        getContentPane().add(fromDateLbl1);
        fromDateLbl1.setBounds(240, 260, 205, 32);
        getContentPane().add(taskIdLbl2);
        taskIdLbl2.setBounds(249, 109, 205, 32);
        getContentPane().add(currentMembersLbl);
        currentMembersLbl.setBounds(530, 420, 205, 32);

        jLabel9.setText("old members");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(44, 380, 75, 16);
        getContentPane().add(oldMemberLbl3);
        oldMemberLbl3.setBounds(243, 374, 205, 32);
        getContentPane().add(currentResourcesLbl);
        currentResourcesLbl.setBounds(520, 520, 205, 25);

        jLabel10.setText("Old resources");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 480, 90, 16);
        getContentPane().add(oldResourcesLbl);
        oldResourcesLbl.setBounds(210, 470, 205, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        tasksManager c= new tasksManager();
        c.show();
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addResourcesIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResourcesIdBtnActionPerformed
        // TODO add your handling code here:
        tempResources.add((String)resourcesIdcmb.getSelectedItem());
         currentResourcesLbl.setText(currentResourcesLbl.getText()+" ,"+(String)resourcesIdcmb.getSelectedItem());
           resourcesIdcmb.removeItemAt(resourcesIdcmb.getSelectedIndex());


    }//GEN-LAST:event_addResourcesIdBtnActionPerformed

    private void addMemberIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberIdBtnActionPerformed
        // TODO add your handling code here:

        tempMembers.add((String)memberIdCmb.getSelectedItem());    
        currentMembersLbl.setText(currentMembersLbl.getText()+" ,"+(String)memberIdCmb.getSelectedItem());
          memberIdCmb.removeItemAt(memberIdCmb.getSelectedIndex());
    }//GEN-LAST:event_addMemberIdBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        Date fromDate=null ;
        try {
            fromDate=  new SimpleDateFormat("dd/MM/yyyy").parse(toDateTxt.getText());
        } catch (ParseException ex) {
            Logger.getLogger(managerEditTask.class.getName()).log(Level.SEVERE, null, ex);
        }
        Task t = Helper.arrTask.get(index);
        String [] oldres = Helper.arrTask.get(index).getResourcesId();

        Helper.arrTask.set(index, new Task(t.getId(),
                t.getProjectId(),
                t.getName(),
                t.getFromDate(),
                fromDate ,
                tempMembers.toArray(new String[tempMembers.size()]) ,
                tempResources.toArray(new String[tempResources.size()]), 
                t.getStatus()));
        
        int id= -1;
        
        
        ArrayList<Integer> released = new ArrayList<>();
         
        for(int k =0;k<oldres.length;k++)
        {
            if(!tempResources.contains(oldres[k]))
            {
                released.add(Integer.parseInt(oldres[k]));
            }
        }
        
        for (int i = 0; i < tempResources.size(); i++) 
        {
            for (int j = 0; j < Helper.arrResource.size(); j++) 
            {
                if(Helper.arrResource.get(j).getId()== Integer.parseInt(tempResources.get(i)))
                {         
                    reservedState r = new reservedState();
                    Resource rr = Helper.arrResource.get(j);
                    r.doAction(rr);
                }
                if(released.contains(Helper.arrResource.get(j).getId()))
                { 
                    availableState aa = new availableState();
                    Resource r3= Helper.arrResource.get(j);
                    aa.doAction(r3);

                }
            }
        }
        
        tasksManager c= new tasksManager();
        c.show();
        this.dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerEditTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerEditTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerEditTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerEditTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerEditTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMemberIdBtn;
    private javax.swing.JButton addResourcesIdBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel currentMembersLbl;
    private javax.swing.JLabel currentResourcesLbl;
    private javax.swing.JLabel fromDateLbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox memberIdCmb;
    private javax.swing.JLabel oldMemberLbl3;
    private javax.swing.JLabel oldResourcesLbl;
    private javax.swing.JLabel projectIdLbl;
    private javax.swing.JLabel projectNameLbl1;
    private javax.swing.JComboBox resourcesIdcmb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel taskIdLbl2;
    private javax.swing.JTextField toDateTxt;
    // End of variables declaration//GEN-END:variables
}
