/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.managment.system;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import static project.managment.system.Helper.arrTask;

/**
 *
 * @author Aya Ebrahim
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    static boolean ceoo ;
    public Report(boolean ceoo) {
        this.ceoo = ceoo;
        initComponents();
        SearchCb.removeAllItems();
        SearchCb.addItem("All projects All Tasks ");
        for (int i = 0; i < Helper.arrProjects.size(); i++) {
            SearchCb.addItem(Helper.arrProjects.get(i).getName());            
        }
        updateTable(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportsCeoTable = new javax.swing.JTable();
        SearchCb = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Reports");

        jButton4.setText("<----");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        reportsCeoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "Project ID", "Title", "From Date", "To Date", "Member ID", "Resources ID", "Status", "Delayed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportsCeoTable);

        SearchCb.setMaximumRowCount(100);
        SearchCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All projects", " " }));
        SearchCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCbActionPerformed(evt);
            }
        });

        jButton1.setText("Display Delayed tasks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SearchCb, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(SearchCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(ceoo){
        CeoHome ch= new CeoHome();
        ch.show();

        }else{
        
        ManagerHome mh = new ManagerHome();
        mh.show();
        }
        this.dispose();

       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SearchCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchCbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = SearchCb.getSelectedIndex();
        updateTable(index);
    }//GEN-LAST:event_jButton1ActionPerformed
  private void updateTable( int pro_index) {                                         
        // TODO add your handling code here:
        DefaultTableModel m =(DefaultTableModel)reportsCeoTable.getModel();
        m.setRowCount(0);
        String Recources="";
        String members="";
        String pattern = "dd/MM/yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        Date now = new Date();  
        if(pro_index == 0)
        {
            
            for(int i=0; i <Helper.arrTask.size();i++)
        {   
            Recources="";
            members="";
            
            String[] x= Helper.arrTask.get(i).getResourcesId();
            for(int j =0;j<Helper.arrTask.get(i).getResourcesId().length;j++)                 
                 Recources += x[j]+",";
             
             String[] xs= Helper.arrTask.get(i).getMemberId();
             for(int j =0;j<Helper.arrTask.get(i).getMemberId().length;j++)                 
                 members += xs[j]+",";
            
             if(Helper.arrTask.get(i).getToDate().compareTo(now)<0&&!Helper.arrTask.get(i).getStatus().equals("Done") )
                    {
                           m.addRow(new java.lang.Object[]{Helper.arrTask.get(i).getId(),
                        Helper.arrTask.get(i).getProjectId(),
                        Helper.arrTask.get(i).getName(),
                        simpleDateFormat.format(Helper.arrTask.get(i).getFromDate()),
                        simpleDateFormat.format(Helper.arrTask.get(i).getToDate()),
                        members,
                        Recources,
                        Helper.arrTask.get(i).getStatus(),
                        "Yes"});
                    }
                    else 
                    {
                         m.addRow(new java.lang.Object[]{Helper.arrTask.get(i).getId(),
                        Helper.arrTask.get(i).getProjectId(),
                        Helper.arrTask.get(i).getName(),
                        simpleDateFormat.format(Helper.arrTask.get(i).getFromDate()),
                        simpleDateFormat.format(Helper.arrTask.get(i).getToDate()),
                        members,
                        Recources,
                        Helper.arrTask.get(i).getStatus(),
                        "No"});
                    }
               }
        
        }else{
           
            for(int i=0; i <Helper.arrTask.size();i++)
        {   
            Recources="";
            members="";
            int n =0;
            String[] x= Helper.arrTask.get(i).getResourcesId();
            for(int j =0;j<Helper.arrTask.get(i).getResourcesId().length;j++)                 
                 Recources += x[j]+",";
             
             String[] xs= Helper.arrTask.get(i).getMemberId();
             for(int j =0;j<Helper.arrTask.get(i).getMemberId().length;j++)                 
                 members += xs[j]+",";
            
             n = Helper.arrProjects.get(pro_index-1).getId();
             if(n==Helper.arrTask.get(i).getProjectId() && Helper.arrTask.get(i).getToDate().compareTo(now)<0&&!Helper.arrTask.get(i).getStatus().equals("Done") )
                    {
                           m.addRow(new java.lang.Object[]{Helper.arrTask.get(i).getId(),
                        Helper.arrTask.get(i).getProjectId(),
                        Helper.arrTask.get(i).getName(),
                        simpleDateFormat.format(Helper.arrTask.get(i).getFromDate()),
                        simpleDateFormat.format(Helper.arrTask.get(i).getToDate()),
                        members,
                        Recources,
                        Helper.arrTask.get(i).getStatus(),
                        "Yes"});
                    }
             
               }
            
    }
  }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report(ceoo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox SearchCb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reportsCeoTable;
    // End of variables declaration//GEN-END:variables
}
